/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package de.tum.in.dss.project;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Pause implements org.apache.thrift.TEnum {
  YES(1),
  NO(2),
  SLEEPING(3);

  private final int value;

  private Pause(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Pause findByValue(int value) { 
    switch (value) {
      case 1:
        return YES;
      case 2:
        return NO;
      case 3:
        return SLEEPING;
      default:
        return null;
    }
  }
}
