/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package de.tum.in.dss.project;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Rating implements org.apache.thrift.TEnum {
  VERY_BAD(1),
  BAD(2),
  OK(3),
  GOOD(4),
  EXCELLENT(5);

  private final int value;

  private Rating(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Rating findByValue(int value) { 
    switch (value) {
      case 1:
        return VERY_BAD;
      case 2:
        return BAD;
      case 3:
        return OK;
      case 4:
        return GOOD;
      case 5:
        return EXCELLENT;
      default:
        return null;
    }
  }
}
