/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package de.tum.in.dss.project;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Speed implements org.apache.thrift.TEnum {
  SLOWER(1),
  OK(2),
  FASTER(3);

  private final int value;

  private Speed(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Speed findByValue(int value) { 
    switch (value) {
      case 1:
        return SLOWER;
      case 2:
        return OK;
      case 3:
        return FASTER;
      default:
        return null;
    }
  }
}
